- name: Cohort Leader
  members:
    - name: Adrienne Soliven
      nickname: Adrienne
      type: Student
      pic: ../assets/png/profile/adrienne_soliven.jpg
- name: People Operations
  members:
    - name: Shenn Tinsay
      nickname: Shenn
      type: Student
      pic: ../assets/png/profile/shenn_tinsay.jpg
    - name: Joshua Manzano
      nickname: Josh
      type: Student
      pic: ../assets/png/profile/joshua_manzano.jpg
    - name: Kyle Santiago
      nickname: Kyle
      type: Student
      pic: ../assets/png/profile/kyle_santiago.jpg
- name: Project Management
  members:
    - name: Geremiah Zachary Marasigan
      nickname: Zach
      type: Student
      pic: ../assets/png/profile/geremiah_marasigan.jpg
    - name: Lynux Ansay
      nickname: Lynux
      type: Student
      pic: ../assets/png/profile/lynux_ansay.jpg
- name: Strategic Communications
  members:
    - name: Miguel Llamas
      nickname: Miggy
      type: Student
      pic: ../assets/png/profile/miguel_llamas.jpg
    - name: Ian Benedict Ona
      nickname: Ian
      type: Student
      pic: ../assets/png/profile/ian_ona.jpg
    - name: Emir Mendoza
      nickname: Emir
      type: Student
      pic: ../assets/png/profile/emir_mendoza.jpg
# - name: Lab Operations
#   members:
#     - name: Tadhg McCarthy
#       nickname: Tadhg
#       role: Lead
#       type: Student
#       pic: ../assets/png/profile/tadhg_mccarthy.jpg
- name: Subject Matter Experts
  members:
    # - name: Jan Christian Blaise Cruz
    #   nickname: Blaise
    #   type: Student
    #   pic: ../assets/png/profile/blaise_cruz.jpg
    #   subject: Machine Learning
    - name: Justin Ricardo
      nickname: Justin
      type: Student
      pic: ../assets/png/profile/justin_ricardo.jpg
      subject: Network Science, Machine Learning
    - name: Adrienne Soliven
      nickname: AD
      type: Student
      pic: ../assets/png/profile/adrienne_soliven.jpg
      subject: Human-Computer Interaction
    - name: Ian Ona
      nickname: Ian
      type: Student
      pic: ../assets/png/profile/ian_ona.jpg
      subject: Complex Systems
- name: Technical Specialists
  members:
    - name: Emir Mendoza
      nickname: Emir
      type: Student
      pic: ../assets/png/profile/emir_mendoza.jpg
      subject: Data Viz