- name: Cohort Leader
  members:
    - name: Giselle Nodalo
      nickname: Giselle
      type: Student
      pic: ../assets/png/profile/giselle_nodalo.jpg
- name: People Operations
  members:
    - name: Julianne Tan
      nickname: Julianne
      role: Lead
      type: Student
      pic: ../assets/png/profile/julianne_tan.jpg
    - name: Krizia Lynn Chiu
      nickname: Krizia
      role: Lead
      type: Student
      pic: ../assets/png/profile/krizia_chiu.jpg
    - name: Joshua Cruzada
      nickname: Josh
      role: Lead
      type: Student
      pic: ../assets/png/profile/joshua_cruzada.jpg
- name: Project Management
  members:
    - name: Jose Luis Diño
      nickname: Luigi
      role: Lead
      type: Student
      pic: ../assets/png/profile/luis_dino.jpg
    - name: Austin Fernandez
      nickname: Austin
      type: Student
      pic: ../assets/png/profile/austin_fernandez.jpg
    - name: Troy Mirafuentes
      nickname: Troy
      type: Student
      pic: ../assets/png/profile/troy_mirafuentes.jpg
- name: Strategic Communications
  members:
    - name: Diane Cruz
      nickname: Diane
      role: Lead
      type: Student
      pic: ../assets/png/profile/diane_cruz.jpg
    - name: Adrienne Solliven
      nickname: AD
      role: Lead
      type: Student
      pic: ../assets/png/profile/adrienne_soliven.jpg
    - name: Luis Lopez
      nickname: Luis
      type: Student
      pic: ../assets/png/profile/luis_lopez.jpg
    - name: Miguel Llamas
      nickname: Miggy
      type: Student
      pic: ../assets/png/profile/miguel_llamas.jpg
    - name: Ian Benedict Ona
      nickname: Ian
      type: Student
      pic: ../assets/png/profile/ian_ona.jpg
    - name: Kaye Ng
      nickname: Kaye
      type: Student
      pic: ../assets/png/profile/kaye_ng.jpg
- name: Lab Operations
  members:
    - name: Jesin Jarod Martinez
      nickname: Jarod
      role: Lead
      type: Student
      pic: ../assets/png/profile/jarod_martinez.jpg
- name: Subject Matter Experts
  members:
    - name: Jan Christian Blaise Cruz
      nickname: Blaise
      type: Student
      pic: ../assets/png/profile/blaise_cruz.jpg
      subject: Machine Learning
    - name: Betlee-Kyle Barraquias
      nickname: Mark
      type: Student
      pic: ../assets/png/profile/mark_barraquias.jpg
      subject: Web Technologies
    - name: Giselle Nodalo
      nickname: Giselle
      type: Student
      pic: ../assets/png/profile/giselle_nodalo.jpg
      subject: UX
- name: Technical Specialists
  members:
    - name: Joshua Cruzada
      nickname: Josh
      type: Student
      pic: ../assets/png/profile/joshua_cruzada.jpg
      subject: Python, Git