- name: Cohort Leader
  members:
    - name: Adrienne Soliven
      nickname: Adrienne
      type: Student
      pic: ../assets/png/profile/adrienne_soliven.jpg
- name: People Operations
  members:
    - name: Shenn Tinsay
      nickname: Shenn
      role: Lead
      type: Student
      pic: ../assets/png/profile/shenn_tinsay.jpg
    - name: Joshua Manzano
      nickname: Josh
      role: Lead
      type: Student
      pic: ../assets/png/profile/joshua_manzano.jpg
    - name: Kyle Santiago
      nickname: Kyle
      role: Lead
      type: Student
      pic: ../assets/png/profile/kyle_santiago.jpg
- name: Project Management
  members:
    - name: Geremiah Zachary Marasigan
      nickname: Zach
      role: Lead
      type: Student
      pic: ../assets/png/profile/geremiah_marasigan.jpg
    - name: Lynux Ansay
      nickname: Lynux
      type: Student
      pic: ../assets/png/profile/lynux_ansay.jpg
- name: Strategic Communications
  members:
    - name: Emir Mendoza
      nickname: Emir
      role: Lead
      type: Student
      pic: ../assets/png/profile/emir_mendoza.jpg
    - name: Miguel Llamas
      nickname: Miggy
      type: Student
      pic: ../assets/png/profile/miguel_llamas.jpg
    - name: Fritz Calimag
      nickname: Fritz
      type: Student
      pic: ../assets/png/profile/fritz_calimag.jpg
    - name: Antonello Santos
      nickname: Nelo
      type: Student
      pic: ../assets/png/profile/antonello_santos.jpg
    - name: Julian De Castro
      nickname: Julian
      type: Student
      pic: ../assets/png/profile/julian_decastro.jpg
    - name: Paolo Delos Reyes
      nickname: Pao
      type: Student
      pic: ../assets/png/profile/paolo_delosreyes.jpg
    - name: Mark Lim
      nickname: Mark
      type: Student
      pic: ../assets/png/profile/mark_lim.jpg
    - name: Jerald Ang
      nickname: Jerald
      type: Student
      pic: ../assets/png/profile/jerald_ang.jpg
- name: Lab Operations
  members:
    - name: Tadhg McCarthy
      nickname: Tadhg
      role: Lead
      type: Student
      pic: ../assets/png/profile/tadhg_mccarthy.jpg
    - name: Romeo Peña
      nickname: Rolo
      type: Student
      pic: ../assets/png/profile/romeo_pena.jpg
- name: Subject Matter Experts
  members:
    - name: Justin Ricardo
      nickname: Justin
      type: Student
      pic: ../assets/png/profile/justin_ricardo.jpg
      subject: Network Science, Machine Learning
    - name: Adrienne Soliven
      nickname: AD
      type: Student
      pic: ../assets/png/profile/adrienne_soliven.jpg
      subject: Human-Computer Interaction
    - name: Ian Ona
      nickname: Ian
      type: Student
      pic: ../assets/png/profile/ian_ona.jpg
      subject: Complex Systems
- name: Technical Specialists
  members:
    - name: Emir Mendoza
      nickname: Emir
      type: Student
      pic: ../assets/png/profile/emir_mendoza.jpg
      subject: Data Viz